services:
  - type: web
    name: whatsapp-interface
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: NODE_ENV
        value: production
    autoDeploy: true
    healthCheckPath: /
    buildFilter:
      paths:
        - src/**/*.{js,jsx,ts,tsx}
        - package.json
        - next.config.js
        - tsconfig.json
        - public/**/* 