services:
  - type: web
    name: whatsapp-interface
    env: node
    region: ohio
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
    healthCheckPath: /
    scaling:
      minInstances: 1
      maxInstances: 1
    buildFilter:
      paths:
        - src/**/*.{js,jsx,ts,tsx}
        - package.json
        - next.config.js
        - tsconfig.json
        - public/**/* 